POST http://localhost:5001/superheroes
Content-Type: application/json

{
    "nickname":"Jeleznffffiy chelsdfsdsdffsdfsdfsdfsdfoveck",
    "realName":"Rav Vlasmffffsdfsdfsdfsdfffan",
    "originDescription":"Blisdddtatdfffelnaysdfsdfa hsdfsdfucpa!",
    "superpowers":"Kek",
    "catch_phrase":"Blisfffddddddtatesdfsdfsdfsdflnaya huzpa!Proso ssdfsfuper!"
}